services:

  # nginx:
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   volumes:
  #     - ./shared/nginx:/var/www/htm
  #   depends_on:
  #     - softether
  #   networks:
  #     - neovpn


  softether:
    build:
      context: ./softether
      dockerfile: Dockerfile
    container_name: softether
    volumes:
      - type: bind
        source: ./shared/softether/.
        target: /home/shared
    command: /bin/sh -c "/usr/local/vpnserver/vpnserver start &&\
                          chmod +x /usr/local/vpnserver/set_default_password_for_vpn_server.exp &&\
                          /usr/local/vpnserver/set_default_password_for_vpn_server.exp &&\
                          /usr/local/vpnserver/vpnserver stop &&\
                          systemctl enable vpnserver &&\
                          systemctl start vpnserver &&\
                          systemctl status vpnserver &&\"
                          tail -F keepRunning"
    ports:
      - 5544:5544
      - 443:443
      - 8888:8888
      - 500:500
      - 4500:4500
      - 1701:1701
      - 1194:1194
      - 5555:5555
    networks:
      - neovpn


  # x-ui:
  #   build:
  #     context: ./x-ui
  #     dockerfile: Dockerfile
  #   container_name: x-ui
  #   networks: 
  #     - neovpn

    
networks:
  neovpn: