services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: neo-nginx
    volumes:
      - ./shared:/var/www/htm
    depends_on:
      - softether
    networks:
      - neovpn
    
networks:
  neovpn: