services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: neo-nginx
    volumes:
      - ./shared/nginx:/var/www/htm
    depends_on:
      - softether
    networks:
      - neovpn

  softether:
    build:
      context: ./softether
      dockerfile: Dockerfile
    container_name: neo-softether
    volumes:
      - ./shared/softether: /app
    networks:
      - neovpn

    
networks:
  neovpn: